name: "Print Message with Level"
description: "A custom action to print a message with a specified level (info, error, debug)."

inputs:
  level:
    description: "The level of the message (info, error, debug)"
    required: true
    default: "info"
  message:
    description: "The message to print"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      shell: bash
      with:
        repository: xctions/log
        ref: main

    - name: Set execute permissions
      shell: bash
      run: chmod +x ./bin/*.sh

    - name: Add bin to PATH
      shell: bash
      run: echo "::add-path::$(pwd)/bin"

    - name: Print message
      shell: bash
      run: |
        level="${{ inputs.level }}"
        message="${{ inputs.message }}"

        case $level in
          info)
            INFO.sh "$message"
            ;;
          error)
            ERR.sh "$message"
            ;;
          debug)
            DEBUG.sh "$message"
            ;;
          *)
            echo "Invalid level: $level. Must be one of: info, error, debug."
            exit 1
            ;;
        esac